/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Wishlist;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-06-03T10:33:57.949Z")

@Validated
@Api(value = "wishlist", description = "the wishlist API")
@RequestMapping(value = "/v1")
public interface WishlistApi {

    @ApiOperation(value = "Add sneakers to wishlist", nickname = "addSneakersToWishlist", notes = "", response = Wishlist.class, tags={ "wishlist", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Wishlist.class),
        @ApiResponse(code = 400, message = "Invalid data in the wishlist") })
    @RequestMapping(value = "/wishlist/",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Wishlist> addSneakersToWishlist(@ApiParam(value = "sneakers to add in the wishlist" ,required=true )  @Valid @RequestBody Wishlist body);


    @ApiOperation(value = "Returns sneakers from user wishlist", nickname = "getUserWishlist", notes = "", response = Wishlist.class, responseContainer = "List", tags={ "wishlist", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Wishlist.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid user ID supplied"),
        @ApiResponse(code = 404, message = "Wishlist not found") })
    @RequestMapping(value = "/wishlist/{userId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Wishlist>> getUserWishlist(@ApiParam(value = "ID of user of whom to return the wishlist",required=true) @PathVariable("userId") String userId);


    @ApiOperation(value = "Removes a sneaker from the wishlist", nickname = "removeSneakerInWishlist", notes = "", tags={ "wishlist", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Sneaker not found") })
    @RequestMapping(value = "/wishlist/remove/{sneakerId}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> removeSneakerInWishlist(@ApiParam(value = "ID of the sneaker to be removed",required=true) @PathVariable("sneakerId") String sneakerId);

}
